# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6523b0e38c6c0e09a9ae128537f16527a1f295f4acdf9080eb46211aff95eaa5c2f35772652ef446a94c9a9595c7a2e950a70048f427fd9658364a141fbe280

test:
  secret_key_base: 7c2bc189609187b8cacc77fd540bf60536b9bd00936a4a1838e6921096a05b31283434f4ce2f32b3315304ed944a327f69ed9a3f7f10a9bc54f2d51241c4d0b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
